CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Topics" (
    "Id" UUID PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Keywords" TEXT,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "News" (
    "Id" UUID PRIMARY KEY,
    "Title" TEXT NOT NULL,
    "Description" TEXT,
    "Topic" TEXT,
    "SourceUrl" TEXT,
    "SourceName" TEXT,
    "IsImportant" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsRead" BOOLEAN NOT NULL DEFAULT FALSE,
    "PublishedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);